@startmindmap
* 手势
** 竞技层
***_ GestureArenaManager 竞技场管理者
***_ GestureArenaMember 竞技场参赛者接口
***_ _GestureArena 竞技场对象
***_ GestureArenaEntry 竞技场信息发送器
** 手势数据层
***_ PointerEvent
** 常用手势
***_ Tap
****_ onTap
****_ onTapCancelsz
****_ onTapDown
*****_ TapDownDetails
******_ localPoaition(相对组件左上角)
******_ globalPosition(相对屏幕左上角)
******_ kind(触电设备类型)
****_ onTapUp
*****_ TapUpDetails
***_ DoubleTap
****_ onDoubleTap
****_ onDoubleTapCancel
***_ LongPress
****_ onLongPressStart
****_ onLongPress
****_ onLongPressMoveUpdate
*****_ offsetFromOrigin 开始触点到当前触点(全局)
*****_ localOffsetFromOrigin 开始触点到当前触点(相对)
****_ onLongPressEnd
*****_ localPosition
*****_ globalPosition
*****_ velocity 结束时速度
****_ onLongPressUp
***_ Pan
****_ onPanDown
****_ onPanStart
*****_ DragStartDetails
******_ sourceTimeStamp
******_ kind
****_ onPanUpdate
*****_ DragUpdateDetails
******_ delta
******_ sourceTimeStamp
******_ primaryDelta
****_ onPanEnd
*****_ DragEndDetails
******_ velocity
******_ primaryVelocity
****_ onPanCancel
***_ scale
****_ onScaleStart
*****_ focalPoint 触电与屏幕接触的焦点(平面左上角)
*****_ localFocalPoint 触电与屏幕接触的初始焦点(组件左上角)
*****_ pointCount 触点个数
****_ onScaleUpdate
*****_ scale 缩放比例
*****_ rotation 旋转角度
****_ onScaleEnd
*****_ velocity 速度
** GestureDetector
***_ Map<Type, GestureRecognizerFactory> gestures 记录需要检测的手势
***_ Type
****_ TapGestureRecognizer
****_ DoubleTapGesturerecognizer
****_ LongPressGestureRecognier
****_ VerticalDragGestureRecognizer
****_ HorizontalDragGestureRecognizer
****_ PanGestureRecognizer
****_ ScaleGestureRecognizer
****_ ForcePressGestureRecognizer
** RawGestureDetector
***_ Map<Type, GestureRecognizerFactory> gestures
***_ HitTestBehavior behavior
***_ RawGestureDetectorState
****_ Map<Type, GestureRecognizer> _recognizer
****_ void syncAll() 维护手势检测器 && 绑定监听
****_ build()
*****_ Listener 手势组件
*****_ PointerEvent 手势事件
*****_ GestureRecognizer 手势识别器
** GestureArenaMember
***_ acceptGesture 通知参赛者处理胜利后逻辑
***_ rejectGesture 通知参赛者处理失败后逻辑
** GestureRecognizer
***_ Object debugOwner 识别器的所有者
***_ PointDeviceKind _kindFilter 触电类型的过滤
***_ Map<int, PointerDeviceKind> _pointerToKind 指针id和指针设备类型映射
***_ addPointer 触点数据注册到手势检测器
***_ isPointerAllowed 是否允许跟踪指针
***_ addAllowedPointer 对event注册
***_ handleNonAllowedPointer 拒绝该触点
***_ dispose 销毁
***_ PointDeviceKind getKindForPointer(int pointer) 得到指针类型
** GestureRecognizer子类
***_ OneSequenceGestureRecognizer
****_ 追踪触点和停止追踪触点
****_ 加入到手势竞技场,获得GestureArenaEntry
****_ resolve && resolvePointer 获胜或失败
****_ OneSequenceGestureRecognizer子类
*****_ PrimaryPointerGestureRecognizer
******_ handleEvent对触点进行偏移检验
******_ acceptGesture && rejectGesture 长按手势检测(Timer)
******_ PrimaryPointerGestureRecognizer子类
*******_ LongPressGestureRecognizer
*******_ BaseTapGestureRecognizer
*****_ ScaleGestureRecognizer
******_ 维护触点Id的队列 _pointerQueue 检测与屏幕接触的点数
******_ 胜利的校验 -> _advanceStateMachine -> 偏移量和状态校验
*****_ DragGestureRecognizer
******_ 核心: handleEvent -> _hasSufficientGlobalDistanceToAccept
******_ DragGestureRecognizer子类
*******_ PanGestureRecognizer
********_ HorizontalDragGestureRecognizer 偏移dx
********_ VerticalDragGestureRecognizer 偏移dy
*******_ VerticalDragGestureRecognizer
*******_ HorizontalDragGestureRecognizer
***_ DoubleTapGesturerecognizer
***_ MultiTapGestureRecognizer
***_ MultiDragGestureRecognizer
** 手势竞技场类
***_ GestureArenaMember参赛者
****_ 所有的手势检测器对象都可以被视为参赛者
***_ _GestureArena 竞技场
****_ List<GestureArenaMember>
****_ isOpen 竞技场是否开放
****_ isHeld 竞技场是否挂起
****_ hasPendingSweep 竞技场是否等待清扫
****_ eagerWinner渴望胜利的参赛者
****_ add(member) 新增一个参赛者并加入到memebers
***_ GestureArenaEntry 竞技场信息发送器 
****_ GestureArenaManager _arena
****_ _pointer 触点id
****_ _member 参赛者
****_ resolve(GestureDisposition disposition) 职责: 向竞技场对象船底参赛者被接受或被拒绝的消息
***_ GestureArenaManager 竞技场管理者
****_ 每个触点对应一个竞技场 Map<int, _GestureArena> _arenas
****_ add(int pointer, GestureArenaMember member) -> _arenas加一组,竞技场_GestureArena加参赛者member
****_ hold(int pointer) -> 找不到pointer对应的竞技场_GestureArena
****_ sweep(int pointer) 未挂起时,根据pointer移除_arenas中对应竞技场 -> pointer的竞技场第一个元素宣判获胜
****_ release(int pointer) 是否挂起,决定是否要sweep
****_ close(int pointer) -> isOpen=false; _tryToResolveArena
****_ 四个裁决方法
*****_ _resolveInFavorOf 移除竞技场,宣布指定member胜利
*****_ _resolveByDefault 移除竞技场,宣布唯一member胜利
*****_ _tryToResolveArena 根据竞技场人数判断
*****_ _resolve 根据disposition对竞技场内的参赛者member进行接受或拒绝
** 手势进入竞技场的过程(以TapGestureRecognizer)
***_ RawGestureDetector
****_ syncAll初始化手势检测映射
****_ 点击,Listener触发[onPointerDown: _handlePointerDown] -> recognizer.addPointer
***_ isPointerAllowed 校验-触点是否允许
****_ isPointerAllowed: TapGestureRecognizer -> GestureDetector
***_ addAllowedPointer 触点注册到手势检测器
****_ _down && _up
***_ startTrackingPointer 追踪触点
****_ 将handleEvent注册到GestureBinding.pointerRouter触点路由
****_ handleEvent接受到该触点被GestureBinding分发的所有事件
***_ 触点的维护
****_ Map<int, GestureArenaEntry> _entries 触点对应竞技场信息发送器
****_ Set<int> _trackedPointers 维护触点
***_ 触点加入竞技场 _addPointerToArena
****_ 通过_addPointerToArena得到GestureArenaEntry(使用GestureBinding.gestureArena将参赛者加入到竞技场)
****_ 没有竞技场会创建竞技场并返回GestureArenaEntry
** 单机手势检测器进入竞技场之后
***_ 延迟任务开启
@endmindmap